#!/usr/bin/env bash
# Shared by build.sh/dev.sh: makes sure cargo and the MinGW linker are on PATH even in a shell
# opened before the one-time setup in ../README.md ran (rustup/winget write to the Windows User
# PATH registry value, which an already-open terminal never re-reads).
set -euo pipefail

if ! command -v cargo >/dev/null 2>&1; then
  for candidate in "$HOME/.cargo/bin" "$USERPROFILE/.cargo/bin"; do
    [ -d "$candidate" ] && export PATH="$candidate:$PATH"
  done
fi

# Find the WinLibs MinGW-w64 install (version-stamped folder name, so glob rather than hardcode).
# $LOCALAPPDATA is a Windows-style (backslash) path - cygpath -u it before using it with bash's
# find/PATH, otherwise the mixed backslash/forward-slash path silently matches nothing and every
# lookup below (dlltool, windres, ...) acts as if MinGW were never installed.
localappdata_posix="$(cygpath -u "$LOCALAPPDATA")"
mingw_pkg=$(find "$localappdata_posix/Microsoft/WinGet/Packages" -maxdepth 1 -type d \
  -iname "BrechtSanders.WinLibs*" 2>/dev/null | head -n1)
mingw_bin="${mingw_pkg:+$mingw_pkg/mingw64/bin}"

if [ -n "$mingw_bin" ] && ! command -v dlltool >/dev/null 2>&1; then
  export PATH="$mingw_bin:$PATH"
fi

if ! command -v cargo >/dev/null 2>&1; then
  echo "[toolchain] cargo not found. Open a new terminal (PATH was updated after install), or" >&2
  echo "[toolchain] see desktop/README.md's one-time setup if Rust isn't installed yet." >&2
  exit 1
fi

# Belt-and-suspenders beyond the PATH export above: pin the GNU target's dlltool as an absolute
# path in a project-local cargo config too, so `cargo`/`rustc` find it even if some future PATH
# edit here is wrong again - cargo always honours this regardless of how it was invoked.
# "dlltool" is not a real top-level [target.*] key despite looking like it'd be natural - the
# stable override is rustc's own -C flag, passed through rustflags. Regenerated every run.
if [ -n "$mingw_bin" ]; then
  cargo_config="$DESKTOP/src-tauri/.cargo/config.toml"
  mkdir -p "$(dirname "$cargo_config")"
  mingw_bin_win="$(cd "$mingw_bin" && pwd -W)"
  cat > "$cargo_config" <<EOF
# Auto-generated by scripts/_toolchain.sh - do not edit, do not commit (see ../../.gitignore).
[target.x86_64-pc-windows-gnu]
linker = "$mingw_bin_win/gcc.exe"
rustflags = ["-C", "dlltool=$mingw_bin_win/dlltool.exe"]
EOF
fi
